server:
  port: 9090
  servlet:    context-path: /banking-app

spring:  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cts_db
    username: root
    password: Shobhit#1  jpa:    hibernate:      naming:         physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy